name: screen_protector
description: Flutter plugin to prevent screenshot and screen recording for iOS and Android. Protect your sensitive data from unauthorized capture.
version: 1.4.2
homepage: https://github.com/prongbang/screen_protector

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.prongbang.screen_protector
        pluginClass: ScreenProtectorPlugin
      ios:
        pluginClass: ScreenProtectorPlugin
        # Add Swift Package Manager support
        swift_package_manager: true
       

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

